# @Author: Brogan Miner <Brogan>
# @Date:   2018-11-18T20:35:38-08:00
# @Email:  brogan.miner@oregonstate.edu
# @Last modified by:   Brogan
# @Last modified time: 2019-01-04T09:07:42-08:00

language: node_js
node_js:
    - "10"

branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_d127a46f8a02_key -iv $encrypted_d127a46f8a02_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv key.pem /tmp/rsa
  - sudo chmod 600 /tmp/rsa


after_success:
  - scp -oStrictHostKeyChecking=no -i /tmp/rsa -rp $TRAVIS_BUILD_DIR/nodeServer.js $TRAVIS_BUILD_DIR/db.js $TRAVIS_BUILD_DIR/ddb.js $TRAVIS_BUILD_DIR/package.json $TRAVIS_BUILD_DIR/data $TRAVIS_BUILD_DIR/controllers $TRAVIS_BUILD_DIR/data ubuntu@ec2-52-39-141-177.us-west-2.compute.amazonaws.com:/home/ubuntu/shared-node-server
  - ssh -oStrictHostKeyChecking=no -i /tmp/rsa ubuntu@ec2-52-39-141-177.us-west-2.compute.amazonaws.com 'cd shared-node-server; npm install; forever stopall; forever start nodeServer.js;'
